CREATE TABLE hive.ecommerce.customers (
    sk_customer BIGINT,
    customer_id VARCHAR,
    first_name VARCHAR,
    last_name VARCHAR,
    name VARCHAR,
    email VARCHAR,
    email_domain VARCHAR,
    phone VARCHAR,
    phone_clean VARCHAR,
    address VARCHAR,
    full_address VARCHAR,
    city VARCHAR,
    country VARCHAR,
    country_code VARCHAR,
    date_of_birth DATE,
    customer_age INTEGER,
    registration_date DATE,
    customer_tenure_days INTEGER,
    last_login_date DATE,
    days_since_last_login INTEGER,
    total_orders INTEGER,
    total_spent DOUBLE,
    avg_spent_per_order DOUBLE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    days_since_update INTEGER,
    inactive_customer BOOLEAN,
    row_hash VARCHAR,
    is_current BOOLEAN,
    effective_from TIMESTAMP,
    effective_to TIMESTAMP,
    is_active BOOLEAN,
    ingestion_timestamp TIMESTAMP,
    creation_year INTEGER,
    creation_month INTEGER
)
WITH (
  format = 'PARQUET',
  external_location = 's3a://ecommerce/curated/customers'
);
